bridges = []
persistence_dir = "./tmp/persistence-deepkey"

[[agents]]
id = "host-agent"
name = "DeepKey Host"
keystore_file = "agent-1.key"
public_address = "HcScIkJGqVKcw83yv7gfTXJ6c5pUzj9jj6g675gEvKqsUxsxt6cDVX8mGR8d49r"


[[dnas]]
file = "./dist/DeepKey.dna.json"
hash = "Qmc4Bu8DYedyhfhcpQJNbdRdTwCJS2mBC6mokX8Pihrxv9"
id = "deepkey"


[[instances]]
agent = "host-agent"
dna = "deepkey"
id = "dpki_happ"
[instances.storage]
path = "./tmp/storage-deepkey"
type = "file"

[[interfaces]]
admin = false
id = "ws interface"

    [interfaces.driver]
    port = 8800
    type = "http"
    [[interfaces.instances]]
    id = "dpki_happ"

[[interfaces]]
admin = true
id = "admin interface"

    [interfaces.driver]
    port = 9300
    type = "http"

[dpki]
instance_id = "dpki_happ"
init_params = '{"revocation_key": "HcSCIgvyd46Q4d9xa4gesx8j5tE7crna8m9U4Z63yzmf5aob6t3mKTNIp8mp8fi","signed_auth_key":"CPhaw45L6MjxPOsVBFsTYkl35hS4h9yRNqsl1fqfNx5P6z6l6WE6aLSrBjD3Dfe3HSg3vNSHtC1QeN0FWBo+DQ=="}'

[logger]
type = "debug"
    [[logger.rules.rules]]
    color = "red"
    exclude = false
    pattern = "^err/"

    [[logger.rules.rules]]
    color = "white"
    exclude = false
    pattern = "^debug/dna"

    [[logger.rules.rules]]
    exclude = true
    pattern = ".*"
