bridges = []
persistence_dir = "./tmp/persistence-deepkey"

[[agents]]
id = "host-agent"
name = "DeepKey Host"
keystore_file = "device-1.key"
public_address = "HcSCjJjIe3sRps4zkoCXuu7sUmEdcc6ncH8uID9fMyy7do8ttaciHiZCibgcvrr"


[[dnas]]
file = "./dist/DeepKey.dna.json"
hash = "Qmc4Bu8DYedyhfhcpQJNbdRdTwCJS2mBC6mokX8Pihrxv9"
id = "deepkey"


[[instances]]
agent = "host-agent"
dna = "deepkey"
id = "dpki_happ"
[instances.storage]
path = "./tmp/storage-deepkey"
type = "file"

[[interfaces]]
admin = false
id = "ws interface"

    [interfaces.driver]
    port = 8800
    type = "http"
    [[interfaces.instances]]
    id = "dpki_happ"

[[interfaces]]
admin = true
id = "admin interface"

    [interfaces.driver]
    port = 9300
    type = "http"

[dpki]
instance_id = "dpki_happ"
init_params = '{"revocation_key": "HcSCiPdMkst9geux7y7kPoVx3W54Ebwkk6fFWjH9V6oIbqi77H4i9qGXRsDcdbi","signed_auth_key":"zJkRXrrbvbzbH96SpapO5lDWoElpzB1rDE+4zbo/VthM/mp9qNKaVsGiVKnHkqT4f5J4MGN+q18xP/hwQUKyDA=="}'

# [network]
# type = "sim1h"
# dynamo_url = "http://localhost:8000"

[logger]
type = "debug"
    [[logger.rules.rules]]
    color = "red"
    exclude = false
    pattern = "^err/"

    [[logger.rules.rules]]
    color = "white"
    exclude = false
    pattern = "^debug/dna"

    [[logger.rules.rules]]
    exclude = true
    pattern = ".*"
