bridges = []
persistence_dir = "./tmp-deepkey/tmp"

[[agents]]
id = "host-agent"
name = "DeepKey Host"
keystore_file = "agent.key"
public_address = "HcSciNw8EPFNprfjnvpoZ97hTYZPb97zdkjqiTmb8epjozf5iC8XoQmxnvdrfea"


[[dnas]]
file = "./dist/DeepKey.dna.json"
hash = "QmaLK3zwzKf3zuidzfs71Wum3b4WJv9s9fx1mh7u2hhGqa"
id = "deepkey"

[[interfaces]]
admin = true
id = "admin interface"

    [interfaces.driver]
    port = 3000
    type = "http"

[[instances]]
agent = "host-agent"
dna = "deepkey"
id = "dpki_happ"
[instances.storage]
path = "./tmp-storage/deepkey"
type = "file"

[dpki]
instance_id = "dpki_happ"
init_params = "{\"revocation_key\": \"HcScIXuxtWI6ttc5gngvQTsDnHtynb5dzyDujh37mNo43nf7ZRB5UZKmR9953pa\"}"

[logger]
type = "debug"
[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"
[[logger.rules.rules]]
color = "green"
exclude = false
pattern = "^debug/dna"
[[logger.rules.rules]]
exclude = true
pattern = ".*"
