bridges = []
persistence_dir = "./.tmp/persistence-deepkey"

[[agents]]
id = "host-agent"
name = "DeepKey Host"
keystore_file = "/home/zo-el/.config/holochain/keys/HcSci9zA73GMmX8z7o4sIKNysTi3tq47gOOfI9w99Iuo68fzaeCd5WKC6goty5a"
public_address = "HcSci9zA73GMmX8z7o4sIKNysTi3tq47gOOfI9w99Iuo68fzaeCd5WKC6goty5a"


[[dnas]]
file = "./dist/DeepKey.dna.json"
hash = "QmTnnNYM2cnjmiZmNBh1rCFPWEaTRZqCNKG8kp1Xk5VZRx"
id = "deepkey"


[[instances]]
agent = "host-agent"
dna = "deepkey"
id = "dpki_happ"
[instances.storage]
path = "./.tmp/storage-deepkey"
type = "file"

[[interfaces]]
admin = false
id = "ws interface"

    [interfaces.driver]
    port = 8800
    type = "websocket"
    [[interfaces.instances]]
    id = "dpki_happ"

[[interfaces]]
admin = true
id = "admin interface"

    [interfaces.driver]
    port = 9300
    type = "http"
    [[interfaces.instances]]
    id = "dpki_happ"

[dpki]
instance_id = "dpki_happ"
init_params = '{"revocation_key": "HcScir75WPx7Vn3swtrYJCSOT5Xocvrbu8wda4aotejdf8b9959Sz65dcKDVaji","signed_auth_key":"CzFHUTnO0vYLo8FgOSjessHTRgGePLiIjBYqHSI85M1R/wIMFNdg5k8uKNmpBJi5JqvUvofc5LbTu3XZ/UpwCg=="}'

[logger]
type = "debug"
    [[logger.rules.rules]]
    color = "red"
    exclude = false
    pattern = "^err/"

    [[logger.rules.rules]]
    color = "white"
    exclude = false
    pattern = "^debug/dna"

    [[logger.rules.rules]]
    exclude = true
    pattern = ".*"
