version: 2

jobs:
  build:
    docker:
    - image: holochain/holonix:latest
    steps:
    - checkout
    - run:
      name: DynamoDB
      command: nix-shell --run dynamodb-memory
      background: true
    - run:
        name: Starting test
        command: nix-shell --run dk-test
