version: 2

jobs:
  build:
    docker:
      - image: holochain/holochain-rust:circle.01.warm.nix
  steps:
    - checkout
    - run:
        command: |
          echo "Starting tests..."
          nix-shell --run hf-test
